name: Deployment
on:  
    push:
    workflow_dispatch:


env: 
  env_dbname: ${{secrets.DBNAME}}

jobs:
  testing:
    runs-on: [windows-latest]
    outputs:
        script_file: ${{steps.publish.outputs.script_file}}
    environment:  testing
    env: 
       username: ${{vars.EUSERNAME}}
               
    steps:
            - name: your name of the db is 
              run: write-host ${{env.env_dbname}}
            - name: your name of the username is 
              run: write-host ${{ENV.username}}
            - name: check out repo
              uses: actions/checkout@v4
            - name: create cache
              id: cache-prems
              uses: actions/cache@v3
              with:
                path: node_modules
                key: dep-cache-${{ hashFiles('./package.json') }}
            - name: git installation
              continue-on-error: true
              run: npm instalation
            - name: send variablename1
              id: publish
              run: |
                $a = "Rajesh"
                write-output "script_file=$a" >> $env:GITHUB_output
  deploy:
        needs: testing
        runs-on: windows-latest
        steps:
            - name: check out repotory
              uses: actions/checkout@v4
            - name: read from another runner1
              run:                
                write-host "My name is ${{needs.testing.outputs.script_file}}"
            - name: restored cache21
              id: cache-prems
              uses: actions/cache@v3
              with:
                path: node_modules  
                key: dep-cache-${{ hashFiles('./package.json') }}
            - name: "check condition"
              if: steps.cache-prems.outputs.cache-hit == 'true'
              run: write-host "cache is true"

                  
 

