name: Deployment
on:  
    push:
      branches:
         - master
    workflow_dispatch:
env: 
  env_dbname: ${{secrets.DBNAME}}
jobs:
  testing:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: windows-latest
    outputs:
        script_file: ${{steps.publish.outputs.script_file}}
    environment:  testing
    env: 
       username: ${{vars.EUSERNAME}}
   
    steps:
            - name : check os  
              if: runner.os == 'windows'              
              run: write-host "os is windows"
            - name: your name of the db is 
              run: write-host ${{env.env_dbname}}
            - name: your name of the username is 
              run: write-host ${{ENV.username}}
            - name: check out repo
              uses: actions/checkout@v4
            - name: create cache
              id: cache-prems
              uses: actions/cache@v3
              with:
                path: node_modules
                key: dep-cache-${{ hashFiles('./package.json') }}
            - name: git installation
              continue-on-error: true
              run: npm instalation
            - name: send variablename
              id: publish
              run: |
                $a = "Rajesh"
                write-output "script_file=$a" >> $env:GITHUB_output
            -  name: upload artifacts
               id: upload_art
               uses: actions/upload-artifacts@v4
               with:
                 path: ${{github.workspace}}\src\test\test123.txt

  deploy:
        needs: testing
        runs-on: windows-latest

        steps:
            - name: check OS
              if: runner.os == 'windows'
              run: write-host "windows"
            - name: check out repotory
              uses: actions/checkout@v4
            - name: download artifacts
              uses: actions/download-artifacts@v4
              with:
                path: ${{github.workspace}}\src\test\test123.txt
            - name: read from another runner1
              run:                
                write-host "My name is ${{needs.testing.outputs.script_file}}"
            - name: restored cache21
              id: cache-prems
              uses: actions/cache@v3
              with:
                path: node_modules  
                key: dep-cache-${{ hashFiles('./package.json') }}
            - name: "check condition"
              if: steps.cache-prems.outputs.cache-hit == 'true'
              run: write-host "cache is true"
  failure: 
    needs: testing   
    if: failure()
    uses: ./.github/workflows/workflow_test.yml
    
                  
 
